name: meta-llama/Meta-Llama-3-8B-Instruct
type: CausalLM
epochs: 1
per_device_batch_size: 1
real_batch_size: 32
bf16: True
eval_epochs: 1
early_stopping_patience: 3
max_length: 2048
logging_steps: 1
learning_rate: 2e-5
