defaults:
  - _self_
  - model: t5base
dry_run: False
gradient_checkpointing: False
flash_attention: True
wandb:
  project: "glue_new"
  name: null
  mode: "online"
deepspeed:
  enabled: False
  config: null
evaluation:
  enabled: False
  task: null
  flash_attention: False
  num_samples: 1
  cleanup: True
  n_workers: 4
  timeout: 3.0
  data_dir: null
  ntrain: 5
monitor:
  enabled: False
  interval_minutes: 5
hydra:
  sweeper:
    params:
      ++dataset_name: mnli
      ++seed: 0
